[package]
name = "rustonic"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
md5 = "0.8.0"
async-compat = "0.2.5"
reqwest = { version = "0.13.1", features = ["stream"] }
log = "0.4.21"
image = "0.25.9"
futures-core = "0.3.31"
bytes = "1.11.1"
futures-util = "0.3.31"
rodio = { version = "0.21.1", features = ["wasm-bindgen", "symphonia-all"] }
tokio = { version = "1.48.0", features = ["rt", "macros", "sync"] }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
env_logger = "0.11.3"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "1.0"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-streams = "0.5"

[[bin]]
name = "rustonic"
path = "src/main.rs"

[build-dependencies]
slint-build = "1.14.1"
